language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-workbox
